typedef struct _PoladvrSetupArgs {
    HANDLE waiting_signal;
    LUID non_pet_privilege;
} PoladvrSetupArgs;

#define FILE_DEVICE_POLADVR 0x0000FA00

#define IOCTL_POLADVR_SETUP     (ULONG)CTL_CODE(FILE_DEVICE_POLADVR, 0x00, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_POLADVR_CHECK     (ULONG)CTL_CODE(FILE_DEVICE_POLADVR, 0x01, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_POLADVR_RELEASE   (ULONG)CTL_CODE(FILE_DEVICE_POLADVR, 0x02, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_POLADVR_CONTINUE  (ULONG)CTL_CODE(FILE_DEVICE_POLADVR, 0x03, METHOD_BUFFERED, FILE_WRITE_DATA)
